#!/bin/bash
# Generate ScummVM engine configuration files
# This script runs during CMake configure to generate:
#   - engines/plugins_table.h
#   - engines/detection_table.h
#
# For the embedded ScummVM core, we statically link only the SCUMM engine
# to keep the binary size manageable and provide Monkey Island support.

set -e

SCUMMVM_PATH="$1"
OUTPUT_PATH="$2"

if [ -z "$SCUMMVM_PATH" ] || [ -z "$OUTPUT_PATH" ]; then
    echo "Usage: $0 <scummvm_path> <output_path>"
    exit 1
fi

# Create output directory
mkdir -p "$OUTPUT_PATH/engines"

# Generate plugins_table.h with SCUMM engine
cat > "$OUTPUT_PATH/engines/plugins_table.h" << 'EOF'
// Auto-generated plugins table for embedded ScummVM
// This file is generated by generate_engines.sh

// Engine plugins - statically linked
LINK_PLUGIN(SCUMM)
EOF

# Generate detection_table.h with SCUMM detection
cat > "$OUTPUT_PATH/engines/detection_table.h" << 'EOF'
// Auto-generated detection table for embedded ScummVM
// This file is generated by generate_engines.sh

// Detection plugins - statically linked
LINK_PLUGIN(SCUMM_DETECTION)
EOF

echo "Engine configuration generated successfully (SCUMM engine enabled)"
