# fetch_verified(<manifest> <base url> <cache dir> <out var>)
#
# Fetches every file a sha256sum-format manifest lists from <base url>/<name> into <cache dir>/<name>,
# once, and checks each against its hash on every run. Sets <out var> to the cached paths, in
# manifest order. Script-mode safe, so scripts/fetch_verified_selftest.sh can drive it.
function(fetch_verified manifest base_url cache_dir out_var)
    set(files "")
    file(STRINGS "${manifest}" lines)
    foreach(line ${lines})
        if(NOT line MATCHES "^([0-9a-f]+)  ([^ ].*)$")
            message(FATAL_ERROR "${manifest}: cannot read '${line}'")
        endif()
        set(hash ${CMAKE_MATCH_1})
        set(name ${CMAKE_MATCH_2})
        set(cached "${cache_dir}/${name}")
        if(NOT EXISTS "${cached}")
            message(STATUS "fetching ${name}")
            file(DOWNLOAD "${base_url}/${name}" "${cached}.part" STATUS status)
            list(GET status 0 code)
            if(code)
                file(REMOVE "${cached}.part")
                message(FATAL_ERROR "cannot fetch ${base_url}/${name}: ${status}")
            endif()
            file(RENAME "${cached}.part" "${cached}")
        endif()
        file(SHA256 "${cached}" actual)
        if(NOT actual STREQUAL hash)
            message(FATAL_ERROR "${cached} has sha256 ${actual}, but ${manifest} expects ${hash}. "
                "Delete it to fetch it again.")
        endif()
        list(APPEND files "${cached}")
    endforeach()
    set(${out_var} ${files} PARENT_SCOPE)
endfunction()
